<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>Sideman.App</RootNamespace>
    <AssemblyTitle>Sideman</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sideman.Core\Sideman.Core.csproj" />
    <ProjectReference Include="..\Sideman.Media\Sideman.Media.csproj" />
  </ItemGroup>

</Project>
